<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fiserv.qabrazil</groupId>
        <artifactId>framework-parent-cucumber</artifactId>
        <version>2025-07-04-20-45-5cb75dfb</version>
    </parent>

    <artifactId>portal-do-cliente</artifactId>

    <properties>
        <!-- Plugins versions -->
        <maven.versions.plugin.version>2.17.1</maven.versions.plugin.version>
        <dom4j.version>2.1.4</dom4j.version>
        <doxia.version>1.11.1</doxia.version>
        <maven.dependency.plugin.version>3.7.1</maven.dependency.plugin.version>
        <!-- Building configuration -->
        <argLine>-Dfile.encoding=UTF-8</argLine>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fiserv.qabrazil</groupId>
            <artifactId>framework-playwright</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fiserv.qabrazil</groupId>
            <artifactId>zephyr-cucumber-plugin</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.1.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-csv -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>1.8</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc11 -->
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc11</artifactId>
            <version>23.8.0.25.04</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.github.bastiaanjansen/otp-java -->
        <dependency>
            <groupId>com.github.bastiaanjansen</groupId>
            <artifactId>otp-java</artifactId>
            <version>2.1.0</version>
        </dependency>
    </dependencies>

    <build>
        <testResources>
            <testResource>
                <directory>features</directory>
                <targetPath>com/fiserv/qabrazil/features</targetPath>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${maven.versions.plugin.version}</version>
                <!-- The following dependency of this plugin is ancient and its version 2 is under development.
                     While they don't migrate to the new org.dom4j, we override it ourselves -->
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.doxia</groupId>
                        <artifactId>doxia-site-renderer</artifactId>
                        <version>${doxia.version}</version>
                        <exclusions>
                            <exclusion>
                                <groupId>dom4j</groupId>
                                <artifactId>dom4j</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.dom4j</groupId>
                        <artifactId>dom4j</artifactId>
                        <version>${dom4j.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <dependencyExcludes></dependencyExcludes>
                    <!--suppress UnresolvedMavenProperty -->
                    <rulesUri>file:///${session.executionRootDirectory}/rules.xml</rulesUri>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <!-- The following dependency of this plugin is ancient and its version 2 is under development.
                     While they don't migrate to the new org.dom4j, we override it ourselves -->
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.doxia</groupId>
                        <artifactId>doxia-site-renderer</artifactId>
                        <version>${doxia.version}</version>
                        <exclusions>
                            <exclusion>
                                <groupId>dom4j</groupId>
                                <artifactId>dom4j</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
                    <dependency>
                        <groupId>org.dom4j</groupId>
                        <artifactId>dom4j</artifactId>
                        <version>${dom4j.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
