package com.fiserv.automation.api.dto;

public class SalesDto {
    public String numeroTransacao;
    public String dataTransacao;
    public String horaTransacao;
    public String comprovante;
    public String codProdutoTransacao;
    public String descProdutoTransacao;
    public String codBandeira;
    public String descBandeira;
    public String codTipoTransacao;
    public String descTipoTransacao;
    public String numeroParcela;
    public String qtdeParcelas;
    public String valorTotalPlano;
    public String codAutorizacao;
    public String numCartao;
    public String numTerminal;
    public String codTipoTerminal;
    public String descTipoTerminal;
    public String codTipoCartao;
    public String descTipoCartao;
    public String valorBrutoParcela;
    public String valorDescontoParcela;
    public String valorLiquidoParcela;
    public String indicadorCredDeb;
    public String indicadorCancelVenda;
    public String numeroParcelado;
    public String numeroResumoVenda;
    public String dataPrevistaPagto;
    public String seuNumero;
    public String eciCode;
    public String cashbackAmount;
    public String reverseInterchange;
    public String valorTotalCancelamento;
    public String statusPagamento;
    public String dataEfetivaPagto;
    public String statusAntecipacao;
    public String numeroOrdemPagto;
    public String indicadorPrepago;
    public String networkToken;
}
