package com.fiserv.qabrazil.enums;

import lombok.Getter;

@Getter
public enum PerfilAcessoEnum {
    BIN(
        "bin"
        ,setUrlPortal("bin")
        ,"master"
        ,"18711403829"
        ,"Bin@12345678"
        ,"125"
        ,setInstituicao("7")
    )
    ,BIN_SECUNDARIO(
        "bin"
        ,setUrlPortal("bin")
        ,"secundario"
        ,"max@afinz"
        ,"Fiserv@123456"
        ,"125"
        ,setInstituicao("7")
    )
    ,BIN_CEDIDOS(
        "bin"
        ,setUrlPortal("bin")
        ,"cedidos"
        ,"18711403829"
        ,"Bin@12345678"
        ,"125"
        ,setInstituicao("7")
    )
    ,BIN_FRANQUEADOR(
        "bin"
        ,setUrlPortal("bin")
        ,"franqueador"
        ,"19078280000189"
        ,"Fiserv@12345"
        ,"125"
        ,setInstituicao("7")
    )
    ,BIN_FRANQUEADO(
        "bin"
        ,setUrlPortal("bin")
        ,"franqueado"
        ,"45524517000118"
        ,"Fiserv@12345"
        ,"125"
        ,setInstituicao("7")
    )
    ,SICREDI(
        "sicredi"
        ,setUrlPortal("sicredi")
        ,"master"
        ,"79750866000170"
        ,"Fiserv@1234567"
        ,"110"
        ,setInstituicao("4")
    )
    ,SICREDI_SECUNDARIO(
        "sicredi"
        ,setUrlPortal("sicredi")
        ,"secundario"
        ,"max@afinz"
        ,"Fiserv@123456"
        ,"110"
        ,setInstituicao("4")
    )
    ,SICREDI_CEDIDOS(
        "sicredi"
        ,setUrlPortal("sicredi")
        ,"cedidos"
        ,"79750866000170"
        ,"Fiserv@1234567"
        ,"110"
        ,setInstituicao("4")
    )
    ,SICREDI_FRANQUEADOR(
        "sicredi"
        ,setUrlPortal("sicredi")
        ,"franqueador"
        ,"72513134000117"
        ,"Fiserv@12345"
        ,"110"
        ,setInstituicao("4")
    )
    ,SICREDI_FRANQUEADO(
        "sicredi"
        ,setUrlPortal("sicredi")
        ,"franqueado"
        ,"79750866000170"
        ,"Fiserv@1234567"
        ,"110"
        ,setInstituicao("4")
    )
    ,AZULZINHA(
        "azulzinha"
        ,setUrlPortal("azulzinha")
        ,"master"
        ,"31561999000171"
        ,"Caixa@123456"
        ,"149"
        ,setInstituicao("7")
    )
    ,AZULZINHA_SECUNDARIO(
        "azulzinha"
        ,setUrlPortal("azulzinha")
        ,"secundario"
        ,"max@afinz"
        ,"Fiserv@123456"
        ,"149"
        ,setInstituicao("7")
    )
    ,AZULZINHA_CEDIDOS(
        "azulzinha"
        ,setUrlPortal("azulzinha")
        ,"cedidos"
        ,"31561999000171"
        ,"Caixa@123456"
        ,"149"
        ,setInstituicao("7")
    )
    ,AZULZINHA_FRANQUEADOR(
        "azulzinha"
        ,setUrlPortal("azulzinha")
        ,"franqueador"
        ,"31561999000171"
        ,"Caixa@123456"
        ,"149"
        ,setInstituicao("7")
    )
    ,AZULZINHA_FRANQUEADO(
        "azulzinha"
        ,setUrlPortal("azulzinha")
        ,"franqueado"
        ,"31561999000171"
        ,"Caixa@123456"
        ,"149"
        ,setInstituicao("7")
    )
    ,AFINZ(
        "afinz"
        ,setUrlPortal("afinz")
        ,"master"
        ,"58530339000180"
        ,"Afinz@123456"
        ,"143"
        ,setInstituicao("10")
    )
    ,AFINZ_SECUNDARIO(
        "afinz"
        ,setUrlPortal("afinz")
        ,"secundario"
        ,"max@afinz"
        ,"Fiserv@123456"
        ,"143"
        ,setInstituicao("10")
    )
    ,AFINZ_CEDIDOS(
        "afinz"
        ,setUrlPortal("afinz")
        ,"cedidos"
        ,"58530339000180"
        ,"Afinz@123456"
        ,"143"
        ,setInstituicao("10")
    )
    ,AFINZ_FRANQUEADOR(
        "afinz"
        ,setUrlPortal("afinz")
        ,"franqueador"
        ,"58530339000180"
        ,"Afinz@123456"
        ,"143"
        ,setInstituicao("10")
    )
    ,AFINZ_FRANQUEADO(
        "afinz"
        ,setUrlPortal("afinz")
        ,"franqueado"
        ,"58530339000180"
        ,"Afinz@123456"
        ,"143"
        ,setInstituicao("10")
    )
    ,CLAROPAY(
        "claropay"
        ,setUrlPortal("portal239")
        ,"master"
        ,"33414095000149"
        ,"Fiserv@12345678"
        ,"239"
        ,setInstituicao("7")
    )
    ,CLAROPAY_SECUNDARIO(
        "claropay"
        ,setUrlPortal("portal239")
        ,"secundario"
        ,"max@afinz"
        ,"Fiserv@123456"
        ,"239"
        ,setInstituicao("7")
    )
    ,CLAROPAY_CEDIDOS(
        "claropay"
        ,setUrlPortal("portal239")
        ,"cedidos"
        ,"33414095000149"
        ,"Fiserv@12345678"
        ,"239"
        ,setInstituicao("7")
    )
    ,CLAROPAY_FRANQUEADOR(
        "claropay"
        ,setUrlPortal("portal239")
        ,"franqueador"
        ,"33414095000149"
        ,"Fiserv@12345678"
        ,"239"
        ,setInstituicao("7")
    ),CLAROPAY_FRANQUEADO(
        "claropay"
        ,setUrlPortal("portal239")
        ,"franqueado"
        ,"33414095000149"
        ,"Fiserv@12345678"
        ,"239"
        ,setInstituicao("7")
    )
    ,BANQI(
        "banqi"
        ,setUrlPortal("banqi")
        ,"master"
        ,"10452495000143"
        ,"Banqi@123456"
        ,"240"
        ,setInstituicao("7")
    )
    ,BANQI_SECUNDARIO(
        "banqi"
        ,setUrlPortal("banqi")
        ,"secundario"
        ,"max@afinz"
        ,"Banqi@123456"
        ,"240"
        ,setInstituicao("7")
    )
    ,BANQI_CEDIDOS(
        "banqi"
        ,setUrlPortal("banqi")
        ,"cedidos"
        ,"10452495000143"
        ,"Banqi@123456"
        ,"240"
        ,setInstituicao("7")
    )
    ,BANQI_FRANQUEADOR(
        "banqi"
        ,setUrlPortal("banqi")
        ,"franqueador"
        ,"10452495000143"
        ,"Banqi@123456"
        ,"240"
        ,setInstituicao("7")
    )
    ,BANQI_FRANQUEADO(
        "banqi"
        ,setUrlPortal("banqi")
        ,"franqueado"
        ,"10452495000143"
        ,"Banqi@123456"
        ,"240"
        ,setInstituicao("7")
    )
    ,CORUJACAPITAL(
        "corujacapital"
        ,setUrlPortal("portal242")
        ,"master"
        ,"39341574000169"
        ,"CorujaPay@951"
        ,"242"
        ,setInstituicao("7")
    )
    ,CORUJACAPITAL_SECUNDARIO(
        "corujacapital"
        ,setUrlPortal("portal242")
        ,"secundario"
        ,"max@afinz"
        ,"CorujaPay@951"
        ,"242"
        ,setInstituicao("7")
    )
    ,CORUJACAPITAL_CEDIDOS(
        "corujacapital"
        ,setUrlPortal("portal242")
        ,"cedidos"
        ,"39341574000169"
        ,"CorujaPay@951"
        ,"242"
        ,setInstituicao("7")
    )
    ,CORUJACAPITAL_FRANQUEADOR(
        "corujacapital"
        ,setUrlPortal("portal242")
        ,"franqueador"
        ,"39341574000169"
        ,"CorujaPay@951"
        ,"242"
        ,setInstituicao("7")
    )
    ,CORUJACAPITAL_FRANQUEADO(
        "corujacapital"
        ,setUrlPortal("portal242")
        ,"franqueado"
        ,"39341574000169"
        ,"CorujaPay@951"
        ,"242"
        ,setInstituicao("7")
    );

    private final String alianca;
    private final String urlPortal;
    private final String perfil;
    private final String usuario;
    private final String senha;
    private final String contratoServico;
    private final String instituicao;

    PerfilAcessoEnum(
     String alianca
    ,String urlPortal
    ,String perfil
    ,String usuario
    ,String senha
    ,String contratoServico
    ,String instituicao){
        this.alianca = alianca;
        this.urlPortal = urlPortal;
        this.perfil = perfil;
        this.usuario = usuario;
        this.senha = senha;
        this.contratoServico = contratoServico;
        this.instituicao = instituicao;
    }

    private static String setUrlPortal(String alianca) {
        return "https://" + alianca + ".qa.portaldocliente.fiserv.com";
    }

    private static String setInstituicao(String instituicao) {
        return String.format("%08d", Integer.parseInt(instituicao));
    }
}